### ISSUE TITLE
path to config.yml file issue

### ISSUE THREAD

**Issue by jk28jan1990** [gante/mmWave-localization-learning#23]
Dear Dr Jose,
I am trying to replicate your work but getting error for path to config.yml error. 
would you be able to provide the extra steps to include path to yml files.  
thank you.

**Comment by gante** [comment]
Hi @jk28jan1990 👋 
Can you paste here the command you're trying to run, as well as the error? Without this information, I am unsure how can I help you :)

**Comment by jk28jan1990** [comment]
Dear Dr @gante, 
![image](https://user-images.githubusercontent.com/78262128/157423741-13a74765-a6d4-4cd2-acc7-6321d82a7e01.png)
please take a look to the screen shot which says: 
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "test_model.py", line 165, in <module>
    main()
  File "test_model.py", line 133, in main
    "The predictions and the labels must have the same number of examples!"
AssertionError: The predictions and the labels must have the same number of examples!

**Comment by gante** [comment]
Interesting, I have never seen that error before. However, the line of the error is close to recent changes, so it might be related to them.

To help me debug it, I want to ask you three pieces of information:
1. Are you using the dataset I provided?
2. Have you made any changes to the code?
3. Can you share the config file you're using to run your experiments?

P.S.: you don't need to be formal, you can call me Joao :)

**Comment by jk28jan1990** [comment]
Dear Dr @gante , 
1. I am using your data set. 
2. I have not made any changes, because I am trying to replicate your work. 
3. 
[cnn_experiment1.txt](https://github.com/gante/mmWave-localization-learning/files/8218005/cnn_experiment1.txt)

**Comment by gante** [comment]
@jk28jan1990 Found the issue and merged the fix. Try pulling from master, it should run now :) please reopen the issue if you keep having problems.

Thank you very much for flagging this issue, it is very important to ensure everyone can run the code without issues 🤗
