### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by workcode-del** [gante/mmWave-localization-learning#27]
Hello, I saw your project and I want to try indoor positioning. Do you have any relevant datasets?
I have obtained an indoor model from the 'Wireless InSite ray-tracing simulator' website. And what should I do with this model to get the dataset, that is how to get the final_table dataset for different scenarios. The file has no suffix, and I don't know what data format it is. I don't know how to get the final_table data through software simulation.

**Comment by gante** [comment]
Hi @workcode-del 👋  

No, sadly I haven't worked with any indoor dataset, so I can't help with suggestions.

As for the file format, I've updated the parsing readme [here](https://github.com/gante/mmWave-localization-learning/blob/master/extra/parsing/README.md), which I believe answers your questions. Let me know if it helped :)

**Comment by workcode-del** [comment]
Thank you very much!Your answer is very helpful to me。

**Comment by gante** [comment]
Great! In that case, I'm going to close the issue. Feel free to reopen if you have further questions!
