### ISSUE TITLE
Could you share the Wireless InSite project file?

### ISSUE THREAD

**Issue by FlotingDream** [gante/mmWave-localization-learning#34]
Could you share the Wireless InSite project file?
Thx!
:)

**Comment by gante** [comment]
Hi @FlotingDream 👋 

I've added a new file to the shared google drive folder, containing the wireless insite project ([link to the folder](https://drive.google.com/drive/folders/1gfbZKCsq4D1tvPzPHLftWljsVaL2pjg_?usp=sharing)).

Bear in mind that these files are ~5 years old, I have no idea if they still work with current versions of Wireless Insite.

**Comment by FlotingDream** [comment]
Thx so much!
